title: OWASP Top 10 Blog
email: your-email@example.com
description: >-
  A personal blog documenting my learning journey with the OWASP Top 10 vulnerabilities and PortSwigger Labs.
baseurl: "/top10-owasp-blog" 
url: "https://haidang17-ia.github.io" 
theme: minima
plugins:
  - jekyll-feed

markdown: kramdown
