title: OWASP Top 10 Blog
description: A personal blog about OWASP Top 10 and PortSwigger labs.
baseurl: "/top10-owasp-blog" 
theme: minima
url: "https://haidang17-ia.github.io"
plugins:
  - jekyll-feed

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      css: "/assets/css/custom.css"
