title: OWASP Top 10 Blog
description: A personal blog about OWASP Top 10 and PortSwigger labs.
theme: jekyll-theme-cayman
baseurl: "/top10-owasp-blog" 
url: "https://haidang17-ia.github.io"
plugins:
  - jekyll-feed
